name: Build, Push, and Update Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'k8s/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'k8s/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/**'

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 966391709212.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: user20-k8s-cluster-repo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 레포지토리의 코드를 체크아웃합니다.
    - name: Checkout repository
      uses: actions/checkout@v3

    # Java Development Kit(JDK) 25을 설정합니다.
    - name: Set up JDK 25
      uses: actions/setup-java@v3
      with:
        java-version: '25'
        distribution: 'temurin'

    # mvnw(Maven Wrapper)에 실행 권한을 부여합니다.
    - name: Grant execute permission for Maven Wrapper
      run: chmod +x ./mvnw

    # Maven 의존성을 캐시하여 빌드 속도를 향상시킵니다.
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    # Maven Wrapper를 사용하여 프로젝트를 빌드. 테스트는 건너뛰고 빌드만 진행.
    - name: Build with Maven Wrapper
      run: ./mvnw package -DskipTests

    # AWS 자격 증명을 설정합니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    # Amazon ECR(Elastic Container Registry)에 로그인합니다.
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    # Docker 이미지를 빌드하고 ECR에 푸시합니다.
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

    # Kubernetes 배포 YAML 파일의 image 태그를 새로 빌드되는 이미지 태그로 업데이트합니다.
    - name: Update Deployment YAML
      env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      run: |
        sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}|" k8s/deployment.yaml

    # 변경사항이 있으면 커밋하고 푸시합니다.
    - name: Commit and push if there are changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add k8s/deployment.yaml
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "Update image tag to $GITHUB_SHA" &&
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        )

